---
title: "Modeling"
author: "Sofia Perez"
date: "2026-05-21"
format: html
editor: visual
---

## setup

```{r}
#| label: packages and data
#| message: false
# read in your packages here
library(tidyverse) # general use
library(here) # file organization
library(janitor) # cleaning data frames
library(readxl) # reading excel files
library(scales) # modifying axis labels
library(ggeffects) # getting model predictions
library(MuMIn) # model selection

# read in your data here
labrynth <- read_csv(here("data",
                             "LagoonLappers_DataSheetES153 - R-Studio Data.csv"))
# clean data
labrynth_clean <- labrynth |> # create new object
  clean_names() # clean column names to lower case and underscores

labrynth_adj <- labrynth_clean |> #create new object for voiding a scpecies
  filter(common_name_plant %in% c("Great Brome Grass", "Scarlet Pimpernel", "Wild Radish","*Coyote Brush"))
```

# Figures

## Figure 1. Sunlight Exposure and Flower Count

```{r}
#| label: Shadow and flower plot
#| warning: false
ggplot(data = labrynth_clean,
       aes(x = shadow_from_tree_root_ft,
       y = flower_bud_count,
       color = plant_species)) +
  geom_point(size = 3.5) +
  labs(title = "Flower bud patterns by tree shadow",
       x = "Shadow length from tree root (ft)",
       y = "Flower bud count",
       color = "Species") +
  theme_light() + # change theme 
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5))
```

## Figure 2. Wind and plant height

```{r}
#| label: Wind speed and plant height
ggplot(data = labrynth_clean,
       aes(x = wind_speed_mph,
           y = height_of_each_plant_species_in,
           color = plant_species)) +
  geom_point(size = 3.5) +
  theme_light() +
  labs(title = "Wind speed relationship with plant growth",
       x = "Wind speed (mph)",
       y = "Plant height (in)",
       color = "Species") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5))
```

## Figure 3. Species height over time

```{r}
#| label: species height over time plot
ggplot(data = labrynth_clean,
       aes(x = date,
           y = height_of_each_plant_species_in,
           color = plant_species)) +
  geom_point(size = 3.5) +
  theme_light() +
  labs(title = "Plant growth by species over time",
       x = "Date",
       y = "Plant height (in)",
       color = "Species") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5))
```
